### PR TITLE
Feature/redmine in subdir

### PR DESCRIPTION
**Pull request by zipkid**
As discussed in https://github.com/johanek/johanek-redmine/issues/32

### CODE REVIEW

**Comment by zipkid** [comment]
I see i have some fixing to do...

**Comment by zipkid** [comment]
I see a lot of overlap between this PR and #27 .
I would like to wait for #27 to be merged so i can pull instead of re-creating all of it in my branch (if this is likely to happen soonish)....

**Comment by UnrealQuester** [comment]
#27 will be merged into master this weekend provided no more changes are necessary.

**Comment by zipkid** [comment]
:+1:

**Comment by zipkid** [comment]
I will close this PR in favour of a new, smaller one.

**Pull request closed without merging**
