### PR TITLE
Add an option to disable vhost creation by the module

### PR DESCRIPTION
**Pull request by clauded**

### CODE REVIEW

**Comment by UnrealQuester** [comment]
Thank you for taking your time to contribute!
Maybe we should have a create_vhost option instead? This would be true by default and avoid the double negative in the condition.
What do you think @johanek?

**Comment by johanek** [comment]
Sounds good. Is this the same as #53?

**Comment by UnrealQuester** [comment]
#53 Fixes a circular reference for vhosts, e.g. #57. This PR also fixes this, but requires manual configuration by the user. However, by giving the user the choice to disable our vhost, they can create their own if they need a more complex config, or just not have any vhosts at all.

**Comment by clauded** [comment]
I think it's the same problem. My patch could certainly be more elegant but it works.

**Comment by clauded** [comment]
That's cleaner! +1

Claude

**Comment by UnrealQuester** [comment]
Ping @clauded, are you planning on changing it to create_vhost yourself or are you okay with me merging this now and changig it myself?

**Comment by clauded** [comment]
Please go ahead! Thanks.

Claude

**Pull request merged**
